apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: composer-ai-config
  namespace: composer-ai-gitops
spec:
  sources:
    - repoURL: https://github.com/aokugel/appOfApps.git
      path: appOfApps
      targetRevision: elastic instance
      helm:
        parameters:
          - name: namespacePrefix
            value: composer-ai-
          - name: clusterDomain
            value: ${SUB_DOMAIN}
        valueFiles:
          - $values/tenants/composer-ai/helm-chart-values/app-of-apps/lab-values.yaml
    - repoURL: 'https://github.com/aokugel/cluster-gitops.git'
      targetRevision: main
      ref: values
