apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: gitops-tenant
    releaseName: composer-ai
    repo: https://redhat-ai-services.github.io/helm-charts/
    version: "0.3.12"
    valuesFile: values.yaml
